apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ea
  template:
    metadata:
      labels:
        name: ea
    spec:
      containers:
        - name: ea
          image: eu.gcr.io/rainchasers/gauge/ea:latest
          env:
            - name: PROJECT_ID
              value: rainchasers
            - name: PUBSUB_TOPIC
              value: gauge
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-writekey
                  key: key
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
