apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      name: store
  template:
    metadata:
      labels:
        name: store
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: service-accn-key
      containers:
        - name: store
          image: ghcr.io/robtuley/rainchasers/store:latest
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: GET_HOSTS_FROM
              value: dns
            - name: PROJECT_ID
              value: rainchasers
            - name: PUBSUB_TOPIC
              value: gauge
            - name: ALGOLIA_APP_ID
              valueFrom:
                secretKeyRef:
                  name: algolia-writekey
                  key: id
            - name: ALGOLIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: algolia-writekey
                  key: key
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-writekey
                  key: key
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
