# this cloud build runs once for monitoring/docs tasks
# requires _SONARCLOUD_KEY variable
steps:
  - name: "newtmitch/sonar-scanner"
    args:
      - "sonar-scanner"
      - "-Dsonar.host.url=https://sonarcloud.io"
      - "-Dsonar.login=${_SONARCLOUD_KEY}"
      - "-Dsonar.projectKey=rainchasers_com.rainchasers.gauge"
      - "-Dsonar.organization=rainchasers"
      - "-Dsonar.sources=."
