# requires a substite variable of _APP to
# specify ea, sepa or firestore to build
steps:
  # compile binary using make
  - name: "golang"
    args: ["make", "${_APP}"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "eu.gcr.io/$PROJECT_ID/gauge/${_APP}:${COMMIT_SHA}", "."]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "eu.gcr.io/$PROJECT_ID/gauge/${_APP}:${COMMIT_SHA}",
        "eu.gcr.io/$PROJECT_ID/gauge/${_APP}:latest",
      ]
  # perform app self-test in docker artefact
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "eu.gcr.io/$PROJECT_ID/gauge/${_APP}:${COMMIT_SHA}"]
  # update k8s deployment to rollout new image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/gauge/${_APP}:${COMMIT_SHA}"]
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "set",
        "image",
        "deployment/rainchasers-${_APP}",
        "${_DEPLOY}=eu.gcr.io/$PROJECT_ID/gauge/${_APP}:${COMMIT_SHA}",
      ]
    env:
      ["CLOUDSDK_COMPUTE_ZONE=europe-west1-c", "CLOUDSDK_CONTAINER_CLUSTER=euc"]
images:
  - "eu.gcr.io/$PROJECT_ID/gauge/${_APP}:${COMMIT_SHA}"
  - "eu.gcr.io/$PROJECT_ID/gauge/${_APP}:latest"
