# requires a substite variable of _DIR to specify the app to build
# (e.g. ea/latest) and _DEPLOY for the actual k8s deployment name
steps:
  # code lint and tests
  - name: "gcr.io/cloud-builders/go"
    args: ["vet", "./..."]
    env: ["PROJECT_ROOT=github.com/rainchasers/com.rainchasers.gauge"]
  - name: "gcr.io/cloud-builders/go"
    args: ["test", "./..."]
    env: ["PROJECT_ROOT=github.com/rainchasers/com.rainchasers.gauge"]
  # compile binary into docker container
  - name: "gcr.io/cloud-builders/go"
    args:
      [
        "build",
        "-a",
        "-tags",
        "netgo",
        "-installsuffix",
        "netgo",
        "-o",
        "./deamon",
        "./${_DIR}",
      ]
    env:
      [
        "PROJECT_ROOT=github.com/rainchasers/com.rainchasers.gauge",
        "CGO_ENABLED=0",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "eu.gcr.io/$PROJECT_ID/gauge/${_DIR}:${COMMIT_SHA}", "."]
  # perform app self-test in docker artefact
  - name: "gcr.io/cloud-builders/docker"
    args: ["run", "eu.gcr.io/$PROJECT_ID/gauge/${_DIR}:${COMMIT_SHA}"]
  # update k8s deployment to rollout new image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/gauge/${_DIR}:${COMMIT_SHA}"]
  - name: gcr.io/cloud-builders/kubectl
    args:
      [
        "set",
        "image",
        "deployment/${_DEPLOY}",
        "${_DEPLOY}=eu.gcr.io/$PROJECT_ID/gauge/${_DIR}:${COMMIT_SHA}",
      ]
    env:
      ["CLOUDSDK_COMPUTE_ZONE=europe-west1-c", "CLOUDSDK_CONTAINER_CLUSTER=euc"]
images:
  - "eu.gcr.io/$PROJECT_ID/gauge/${_DIR}:${COMMIT_SHA}"
