# requires a substite variable of _DIR to specify the app to build
# e.g. ea/latest
steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["vet", "./..."]
    env: ["PROJECT_ROOT=github.com/rainchasers/com.rainchasers.gauge"]
  - name: "gcr.io/cloud-builders/go"
    args: ["test", "./..."]
    env: ["PROJECT_ROOT=github.com/rainchasers/com.rainchasers.gauge"]
  - name: "gcr.io/cloud-builders/go"
    args: ["build", "-o", "./deamon", "./${_DIR}"]
    env: ["PROJECT_ROOT=github.com/rainchasers/com.rainchasers.gauge"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "eu.gcr.io/$PROJECT_ID/gauge/${_DIR}:${COMMIT_SHA}", "."]
images:
  - "eu.gcr.io/$PROJECT_ID/gauge/${_DIR}:${COMMIT_SHA}"
