apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rainchasers-bigquery
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rainchasers-bigquery
  template:
    metadata:
      labels:
        name: rainchasers-bigquery
    spec:
      containers:
      - name: rainchasers-bigquery
        image: eu.gcr.io/tuleyprod/com.rainchasers.gauge/bigquery:latest
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: PROJECT_ID
          value: tuleyprod
        - name: LATEST_PUBSUB_TOPIC
          value: com.rainchasers.gauge.latest
        - name: HISTORY_PUBSUB_TOPIC
          value: com.rainchasers.gauge.history
        - name: BUCKET_NAME
          value: com-rainchasers-gauge-csv
        - name: BIGQUERY_DATASET
          value: rainchasers
        - name: BIGQUERY_TABLE
          value: gauge_reading
        - name: MIN_BATCH_SIZE
          value: "3000"
        - name: MIN_BATCH_SECONDS
          value: "1200"