apiVersion: v1
kind: ReplicationController
metadata:
  name: gauge-bigquery
  labels:
    name: gauge-bigquery
spec:
  replicas: 1
  selector:
    name: gauge-bigquery
  template:
    metadata:
      labels:
        name: gauge-bigquery
    spec:
      containers:
      - name: gauge-bigquery-v9
        image: quay.io/rainchasers/gauge_bigquery:v9
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: PROJECT_ID
          value: tuleyprod
        - name: PUBSUB_TOPIC
          value: com.rainchasers.gauge.latest
        - name: BUCKET_NAME
          value: com-rainchasers-gauge-csv
        - name: BIGQUERY_DATASET
          value: rainchasers
        - name: BIGQUERY_TABLE
          value: gauge_reading
        - name: SNAPSHOT_BATCH_SIZE
          value: 1000
