apiVersion: v1
kind: ReplicationController
metadata:
  name: gauge-bigquery
  labels:
    name: gauge-bigquery
spec:
  replicas: 1
  selector:
    name: gauge-bigquery
  template:
    metadata:
      labels:
        name: gauge-bigquery
    spec:
      containers:
      - name: gauge-bigquery-v27
        image: quay.io/rainchasers/gauge_bigquery:v27
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: PROJECT_ID
          value: tuleyprod
        - name: LATEST_PUBSUB_TOPIC
          value: com.rainchasers.gauge.latest
        - name: HISTORY_PUBSUB_TOPIC
          value: com.rainchasers.gauge.history
        - name: BUCKET_NAME
          value: com-rainchasers-gauge-csv
        - name: BIGQUERY_DATASET
          value: rainchasers
        - name: BIGQUERY_TABLE
          value: gauge_reading
        - name: MIN_BATCH_SIZE
          value: "3000"
        - name: MIN_BATCH_SECONDS
          value: "1200"
