apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrw
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nrw
  template:
    metadata:
      labels:
        name: nrw
    spec:
      containers:
        - name: nrw
          image: eu.gcr.io/rainchasers/gauge/nrw:latest
          env:
            - name: PROJECT_ID
              value: rainchasers
            - name: PUBSUB_TOPIC
              value: gauge
            - name: NRW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nrw-apikey
                  key: key
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-writekey
                  key: key
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
