apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrw
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nrw
  template:
    metadata:
      labels:
        name: nrw
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: service-accn-key
      containers:
        - name: nrw
          image: ghcr.io/robtuley/rainchasers/nrw:latest
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: PROJECT_ID
              value: rainchasers
            - name: PUBSUB_TOPIC
              value: gauge
            - name: NRW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nrw-apikey
                  key: key
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-writekey
                  key: key
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
