apiVersion: v1
kind: Deployment
metadata:
  name: rainchasers-sepa
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rainchasers-sepa
  template:
    metadata:
      labels:
        name: rainchasers-sepa
    spec:
      containers:
        - name: rainchasers-sepa
          image: eu.gcr.io/tuleyprod/gauge/sepa:latest
          env:
            - name: PROJECT_ID
              value: tuleyprod
            - name: PUBSUB_TOPIC
              value: com.rainchasers.gauge
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-writekey
                  key: key
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
