apiVersion: v1
kind: Service
metadata:
  name: com-rainchasers-api-internal
  labels:
    name: com-rainchasers-api-internal
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    name: rainchasers-api