name: Build
on:
  release:
    types: [published]
    
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Generate code
        run: go generate ./...

      - name: Run tests
        run: go test -race ./...

      - name: Build ea
        run: go build -ldflags "-s -w -X main.build=${{ GITHUB_SHA }}" -a -installsuffix netgo -tags netgo -o ./app ./cmd/ea

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: robtuley/rainchasers-content/ea
          tag_with_ref: true
