name: Build
on:
  release:
    types: [published]
    
jobs:
  build_and_push:
    name: Build then push to GitHub registry
    strategy:
      matrix:
        cmd: [ea, sepa, nrw, store, web]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Generate code
        run: go generate ./...

      - name: Get the version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build cmd
        run: go build -ldflags "-s -w -X main.version=${{ steps.version.outputs.VERSION }}" -a -installsuffix netgo -tags netgo -o ./app ./cmd/${{ matrix.cmd }}

      - name: Build and push to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            "ghcr.io/${{ github.repository }}/${{ matrix.cmd }}:${{ steps.version.outputs.VERSION }}"
            "ghcr.io/${{ github.repository }}/${{ matrix.cmd }}:latest"