name: Build
on:
  release:
    types: [published]
    
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Generate code
        run: go generate ./...

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build ea
        run: go build -ldflags "-s -w -X main.build=${{ steps.get_version.outputs.VERSION }}" -a -installsuffix netgo -tags netgo -o ./app ./cmd/ea

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            "ghcr.io/${{ github.repository_owner }}/rainchasers-ea:${{ steps.get_version.outputs.VERSION }}"
            "ghcr.io/${{ github.repository_owner }}/rainchasers-ea:latest"

